version: '2.2'

services:
  #The webserver
  rentman-assessments-web:
    image: rentman/assessments
    build:
      context: ./
      dockerfile: ./deployment/dockerfiles/rentman-assessments-web/Dockerfile
    ports:
      - "7000:80"
    volumes:
      - ./app:/var/www
    env_file:
      - ./deployment/env/environment.env
    networks:
      - rentman-assessments-network
  rentman-assessments-db:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./deployment/assets/mysql/assessment.sql:/docker-entrypoint-initdb.d/assessment.sql
      - rentman-assessments-db-volume:/var/lib/mysql
      - ./deployment/assets/mysql/config-file.cnf:/etc/mysql/conf.d/config-file.cnf
    env_file:
      - ./deployment/env/environment.env
    networks:
      - rentman-assessments-network
  composer:
    restart: 'no'
    image: composer:1.10
    command: install
    volumes:
      - ./app:/app
  rentman-assessments-phymyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    ports:
      - "7001:80"
    env_file:
      - ./deployment/env/environment.env
    networks:
      - rentman-assessments-network
networks:
  rentman-assessments-network:
    name: rentman-assessments-network
volumes:
  rentman-assessments-db-volume:
